export type WeaponCatalogClass = "sword" | "claymore" | "polearm" | "bow" | "catalyst";
export type WeaponCatalogTier = "five_star" | "four_star" | "three_star" | "two_star" | "one_star";

export type WeaponCatalogEntry = {
  id: string;
  enkaItemId: number;
  name: string;
  tier: WeaponCatalogTier;
  weaponClass: WeaponCatalogClass;
  iconAssetName: string;
};

// Source: https://genshin-db-api.vercel.app/api/v5/weapons?query=names&matchCategories=true&verboseCategories=true&resultLanguage=English
export const WEAPON_CATALOG = [
  { id: 'absolution', enkaItemId: 11515, name: "Absolution", tier: 'five_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Estoc" },
  { id: 'aquilaFavonia', enkaItemId: 11501, name: "Aquila Favonia", tier: 'five_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Falcon" },
  { id: 'athameArtis', enkaItemId: 11518, name: "Athame Artis", tier: 'five_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Motsognir" },
  { id: 'azurelight', enkaItemId: 11517, name: "Azurelight", tier: 'five_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_OuterSword" },
  { id: 'freedomSworn', enkaItemId: 11503, name: "Freedom-Sworn", tier: 'five_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Widsith" },
  { id: 'haran', enkaItemId: 11510, name: "Haran Geppaku Futsu", tier: 'five_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Amenoma" },
  { id: 'keyOfKhajNisut', enkaItemId: 11511, name: "Key of Khaj-Nisut", tier: 'five_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Deshret" },
  { id: 'lightOfFoliarIncision', enkaItemId: 11512, name: "Light of Foliar Incision", tier: 'five_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Ayus" },
  { id: 'lightbearingMoonshard', enkaItemId: 11519, name: "Lightbearing Moonshard", tier: 'five_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_SilverwareSaw" },
  { id: 'mistsplitterReforged', enkaItemId: 11509, name: "Mistsplitter Reforged", tier: 'five_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Narukami" },
  { id: 'peakPatrol', enkaItemId: 11516, name: "Peak Patrol Song", tier: 'five_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_XochitlsTube" },
  { id: 'primordialJadeCutter', enkaItemId: 11505, name: "Primordial Jade Cutter", tier: 'five_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Morax" },
  { id: 'skywardBlade', enkaItemId: 11502, name: "Skyward Blade", tier: 'five_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Dvalin" },
  { id: 'splendor', enkaItemId: 11513, name: "Splendor of Tranquil Waters", tier: 'five_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Regalis" },
  { id: 'summitShaper', enkaItemId: 11504, name: "Summit Shaper", tier: 'five_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Kunwu" },
  { id: 'urakuMisugiri', enkaItemId: 11514, name: "Uraku Misugiri", tier: 'five_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Needle" },
  { id: 'amenomaKageuchi', enkaItemId: 11414, name: "Amenoma Kageuchi", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Bakufu" },
  { id: 'blackcliffLongsword', enkaItemId: 11408, name: "Blackcliff Longsword", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Blackrock" },
  { id: 'calamityOfEshu', enkaItemId: 11432, name: "Calamity of Eshu", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_SacrificialNgombe" },
  { id: 'cinnabarSpindle', enkaItemId: 11415, name: "Cinnabar Spindle", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Opus" },
  { id: 'favoniusSword', enkaItemId: 11401, name: "Favonius Sword", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Zephyrus" },
  { id: 'festeringDesire', enkaItemId: 11413, name: "Festering Desire", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Magnum" },
  { id: 'finaleOfTheDeep', enkaItemId: 11425, name: "Finale of the Deep", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Vorpal" },
  { id: 'fleuveCendreFerryman', enkaItemId: 11426, name: "Fleuve Cendre Ferryman", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Machination" },
  { id: 'fluteOfEzpitzal', enkaItemId: 11431, name: "Flute of Ezpitzal", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Isikhulu" },
  { id: 'ironSting', enkaItemId: 11407, name: "Iron Sting", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Exotic" },
  { id: 'kagotsurubeIsshin', enkaItemId: 11416, name: "Kagotsurube Isshin", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Youtou" },
  { id: 'lionSRoar', enkaItemId: 11405, name: "Lion\u0027s Roar", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Rockkiller" },
  { id: 'moonweaverSDawn', enkaItemId: 11434, name: "Moonweaver\u0027s Dawn", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Miekka" },
  { id: 'prizedIsshinBlade', enkaItemId: 11419, name: "Prized Isshin Blade", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_YoutouEnchanted" },
  { id: 'prototypeRancour', enkaItemId: 11406, name: "Prototype Rancour", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Proto" },
  { id: 'royalLongsword', enkaItemId: 11404, name: "Royal Longsword", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Theocrat" },
  { id: 'sacrificialSword', enkaItemId: 11403, name: "Sacrificial Sword", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Fossil" },
  { id: 'sapwoodBlade', enkaItemId: 11417, name: "Sapwood Blade", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Arakalari" },
  { id: 'serenitySCall', enkaItemId: 11433, name: "Serenity\u0027s Call", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Ilmarinen" },
  { id: 'sturdyBone', enkaItemId: 11430, name: "Sturdy Bone", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Umpakati" },
  { id: 'swordOfDescension', enkaItemId: 11412, name: "Sword of Descension", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Psalmus" },
  { id: 'swordOfNarzissenkreuz', enkaItemId: 11428, name: "Sword of Narzissenkreuz", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Purewill" },
  { id: 'theAlleyFlash', enkaItemId: 11410, name: "The Alley Flash", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Outlaw" },
  { id: 'theBlackSword', enkaItemId: 11409, name: "The Black Sword", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Bloodstained" },
  { id: 'theDockhandSAssistant', enkaItemId: 11427, name: "The Dockhand\u0027s Assistant", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Mechanic" },
  { id: 'theFlute', enkaItemId: 11402, name: "The Flute", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Troupe" },
  { id: 'toukabouShigure', enkaItemId: 11422, name: "Toukabou Shigure", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Kasabouzu" },
  { id: 'wolfFang', enkaItemId: 11424, name: "Wolf-Fang", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Boreas" },
  { id: 'xiphosMoonlight', enkaItemId: 11418, name: "Xiphos\u0027 Moonlight", tier: 'four_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Pleroma" },
  { id: 'coolSteel', enkaItemId: 11301, name: "Cool Steel", tier: 'three_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Steel" },
  { id: 'darkIronSword', enkaItemId: 11304, name: "Dark Iron Sword", tier: 'three_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Darker" },
  { id: 'filletBlade', enkaItemId: 11305, name: "Fillet Blade", tier: 'three_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Sashimi" },
  { id: 'harbingerOfDawn', enkaItemId: 11302, name: "Harbinger of Dawn", tier: 'three_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Dawn" },
  { id: 'skyriderSword', enkaItemId: 11306, name: "Skyrider Sword", tier: 'three_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Mitsurugi" },
  { id: 'travelerSHandySword', enkaItemId: 11303, name: "Traveler\u0027s Handy Sword", tier: 'three_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Traveler" },
  { id: 'silverSword', enkaItemId: 11201, name: "Silver Sword", tier: 'two_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Silver" },
  { id: 'dullBlade', enkaItemId: 11101, name: "Dull Blade", tier: 'one_star', weaponClass: 'sword', iconAssetName: "UI_EquipIcon_Sword_Blunt" },
  { id: 'blazingSun', enkaItemId: 12514, name: "A Thousand Blazing Suns", tier: 'five_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_RadianceSword" },
  { id: 'beaconOfTheReedSea', enkaItemId: 12511, name: "Beacon of the Reed Sea", tier: 'five_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Deshret" },
  { id: 'fangOfTheMountainKing', enkaItemId: 12513, name: "Fang of the Mountain King", tier: 'five_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_EmeraldSword" },
  { id: 'gestOfTheMightyWolf', enkaItemId: 12515, name: "Gest of the Mighty Wolf", tier: 'five_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_EnsisAquilonis" },
  { id: 'redhornStonethresher', enkaItemId: 12510, name: "Redhorn Stonethresher", tier: 'five_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Itadorimaru" },
  { id: 'skywardPride', enkaItemId: 12501, name: "Skyward Pride", tier: 'five_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Dvalin" },
  { id: 'songOfBrokenPines', enkaItemId: 12503, name: "Song of Broken Pines", tier: 'five_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Widsith" },
  { id: 'theUnforged', enkaItemId: 12504, name: "The Unforged", tier: 'five_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Kunwu" },
  { id: 'verdict', enkaItemId: 12512, name: "Verdict", tier: 'five_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_GoldenVerdict" },
  { id: 'wolfSGravestone', enkaItemId: 12502, name: "Wolf\u0027s Gravestone", tier: 'five_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Wolfmound" },
  { id: 'ultimateOverlordSMegaMagicSword', enkaItemId: 12426, name: "\"Ultimate Overlord\u0027s Mega Magic Sword\"", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Champion" },
  { id: 'akuoumaru', enkaItemId: 12416, name: "Akuoumaru", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Maria" },
  { id: 'blackcliffSlasher', enkaItemId: 12408, name: "Blackcliff Slasher", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Blackrock" },
  { id: 'earthShaker', enkaItemId: 12431, name: "Earth Shaker", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Isikhulu" },
  { id: 'favoniusGreatsword', enkaItemId: 12401, name: "Favonius Greatsword", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Zephyrus" },
  { id: 'flameForgedInsight', enkaItemId: 12432, name: "Flame-Forged Insight", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Polilith" },
  { id: 'forestRegalia', enkaItemId: 12417, name: "Forest Regalia", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Arakalari" },
  { id: 'fruitfulHook', enkaItemId: 12430, name: "Fruitful Hook", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Umpakati" },
  { id: 'katsuragikiriNagamasa', enkaItemId: 12414, name: "Katsuragikiri Nagamasa", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Bakufu" },
  { id: 'lithicBlade', enkaItemId: 12410, name: "Lithic Blade", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Lapis" },
  { id: 'luxuriousSeaLord', enkaItemId: 12412, name: "Luxurious Sea-Lord", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_MillenniaTuna" },
  { id: 'mailedFlower', enkaItemId: 12418, name: "Mailed Flower", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Fleurfair" },
  { id: 'makhairaAquamarine', enkaItemId: 12415, name: "Makhaira Aquamarine", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Pleroma" },
  { id: 'masterKey', enkaItemId: 12433, name: "Master Key", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Ilmarinen" },
  { id: 'portablePowerSaw', enkaItemId: 12427, name: "Portable Power Saw", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Mechanic" },
  { id: 'prototypeArchaic', enkaItemId: 12406, name: "Prototype Archaic", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Proto" },
  { id: 'rainslasher', enkaItemId: 12405, name: "Rainslasher", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Perdue" },
  { id: 'royalGreatsword', enkaItemId: 12404, name: "Royal Greatsword", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Theocrat" },
  { id: 'sacrificialGreatsword', enkaItemId: 12403, name: "Sacrificial Greatsword", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Fossil" },
  { id: 'serpentSpine', enkaItemId: 12409, name: "Serpent Spine", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Kione" },
  { id: 'snowTombedStarsilver', enkaItemId: 12411, name: "Snow-Tombed Starsilver", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Dragonfell" },
  { id: 'talkingStick', enkaItemId: 12424, name: "Talking Stick", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_BeastTamer" },
  { id: 'theBell', enkaItemId: 12402, name: "The Bell", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Troupe" },
  { id: 'tidalShadow', enkaItemId: 12425, name: "Tidal Shadow", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Vorpal" },
  { id: 'whiteblind', enkaItemId: 12407, name: "Whiteblind", tier: 'four_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Exotic" },
  { id: 'bloodtaintedGreatsword', enkaItemId: 12302, name: "Bloodtainted Greatsword", tier: 'three_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Siegfry" },
  { id: 'debateClub', enkaItemId: 12305, name: "Debate Club", tier: 'three_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Reasoning" },
  { id: 'ferrousShadow', enkaItemId: 12301, name: "Ferrous Shadow", tier: 'three_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Glaive" },
  { id: 'skyriderGreatsword', enkaItemId: 12306, name: "Skyrider Greatsword", tier: 'three_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Mitsurugi" },
  { id: 'whiteIronGreatsword', enkaItemId: 12303, name: "White Iron Greatsword", tier: 'three_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Tin" },
  { id: 'oldMercSPal', enkaItemId: 12201, name: "Old Merc\u0027s Pal", tier: 'two_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Oyaji" },
  { id: 'wasterGreatsword', enkaItemId: 12101, name: "Waster Greatsword", tier: 'one_star', weaponClass: 'claymore', iconAssetName: "UI_EquipIcon_Claymore_Aniki" },
  { id: 'bloodsoakedRuins', enkaItemId: 13516, name: "Bloodsoaked Ruins", tier: 'five_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_TummaLyhty" },
  { id: 'calamityQueller', enkaItemId: 13507, name: "Calamity Queller", tier: 'five_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Santika" },
  { id: 'crimsonMoonSSemblance', enkaItemId: 13512, name: "Crimson Moon\u0027s Semblance", tier: 'five_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_BloodMoon" },
  { id: 'engulfingLightning', enkaItemId: 13509, name: "Engulfing Lightning", tier: 'five_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Narukami" },
  { id: 'fracturedHalo', enkaItemId: 13515, name: "Fractured Halo", tier: 'five_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Perdix" },
  { id: 'lumidouceElegy', enkaItemId: 13513, name: "Lumidouce Elegy", tier: 'five_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Muguet" },
  { id: 'primordialJadeWingedSpear', enkaItemId: 13505, name: "Primordial Jade Winged-Spear", tier: 'five_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Morax" },
  { id: 'skywardSpine', enkaItemId: 13502, name: "Skyward Spine", tier: 'five_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Dvalin" },
  { id: 'homa', enkaItemId: 13501, name: "Staff of Homa", tier: 'five_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Homa" },
  { id: 'staffOfTheScarletSands', enkaItemId: 13511, name: "Staff of the Scarlet Sands", tier: 'five_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Deshret" },
  { id: 'symphonistOfScents', enkaItemId: 13514, name: "Symphonist of Scents", tier: 'five_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Trident" },
  { id: 'vortexVanquisher', enkaItemId: 13504, name: "Vortex Vanquisher", tier: 'five_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Kunwu" },
  { id: 'theCatch', enkaItemId: 13415, name: "\"The Catch\"", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Mori" },
  { id: 'balladOfTheFjords', enkaItemId: 13424, name: "Ballad of the Fjords", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Shanty" },
  { id: 'blackcliffPole', enkaItemId: 13404, name: "Blackcliff Pole", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Blackrock" },
  { id: 'crescentPike', enkaItemId: 13403, name: "Crescent Pike", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Exotic" },
  { id: 'deathmatch', enkaItemId: 13405, name: "Deathmatch", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Gladiator" },
  { id: 'dialoguesOfTheDesertSages', enkaItemId: 13426, name: "Dialogues of the Desert Sages", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Caduceus" },
  { id: 'dragonSBane', enkaItemId: 13401, name: "Dragon\u0027s Bane", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Stardust" },
  { id: 'dragonspineSpear', enkaItemId: 13409, name: "Dragonspine Spear", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Everfrost" },
  { id: 'favoniusLance', enkaItemId: 13407, name: "Favonius Lance", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Zephyrus" },
  { id: 'footprintOfTheRainbow', enkaItemId: 13431, name: "Footprint of the Rainbow", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Isikhulu" },
  { id: 'kitainCrossSpear', enkaItemId: 13414, name: "Kitain Cross Spear", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Bakufu" },
  { id: 'lithicSpear', enkaItemId: 13406, name: "Lithic Spear", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Lapis" },
  { id: 'missiveWindspear', enkaItemId: 13419, name: "Missive Windspear", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Windvane" },
  { id: 'moonpiercer', enkaItemId: 13417, name: "Moonpiercer", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Arakalari" },
  { id: 'mountainBracingBolt', enkaItemId: 13430, name: "Mountain-Bracing Bolt", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Umpakati" },
  { id: 'prospectorSDrill', enkaItemId: 13427, name: "Prospector\u0027s Drill", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Mechanic" },
  { id: 'prospectorSShovel', enkaItemId: 13433, name: "Prospector\u0027s Shovel", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Ilmarinen" },
  { id: 'prototypeStarglitter', enkaItemId: 13402, name: "Prototype Starglitter", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Proto" },
  { id: 'rightfulReward', enkaItemId: 13425, name: "Rightful Reward", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Vorpal" },
  { id: 'royalSpear', enkaItemId: 13408, name: "Royal Spear", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Theocrat" },
  { id: 'sacrificerSStaff', enkaItemId: 13434, name: "Sacrificer\u0027s Staff", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Krivule" },
  { id: 'tamayurateiNoOhanashi', enkaItemId: 13432, name: "Tamayuratei no Ohanashi", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Aoandon" },
  { id: 'wavebreakerSFin', enkaItemId: 13416, name: "Wavebreaker\u0027s Fin", tier: 'four_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Maria" },
  { id: 'blackTassel', enkaItemId: 13303, name: "Black Tassel", tier: 'three_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Noire" },
  { id: 'halberd', enkaItemId: 13302, name: "Halberd", tier: 'three_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Halberd" },
  { id: 'whiteTassel', enkaItemId: 13301, name: "White Tassel", tier: 'three_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Ruby" },
  { id: 'ironPoint', enkaItemId: 13201, name: "Iron Point", tier: 'two_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Rod" },
  { id: 'beginnerSProtector', enkaItemId: 13101, name: "Beginner\u0027s Protector", tier: 'one_star', weaponClass: 'polearm', iconAssetName: "UI_EquipIcon_Pole_Gewalt" },
  { id: 'amosBow', enkaItemId: 15502, name: "Amos\u0027 Bow", tier: 'five_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Amos" },
  { id: 'aquaSimulacra', enkaItemId: 15508, name: "Aqua Simulacra", tier: 'five_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Kirin" },
  { id: 'astralVulture', enkaItemId: 15514, name: "Astral Vulture\u0027s Crimson Plumage", tier: 'five_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Qoyllorsnova" },
  { id: 'elegyForTheEnd', enkaItemId: 15503, name: "Elegy for the End", tier: 'five_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Widsith" },
  { id: 'hunterSPath', enkaItemId: 15511, name: "Hunter\u0027s Path", tier: 'five_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Ayus" },
  { id: 'polarStar', enkaItemId: 15507, name: "Polar Star", tier: 'five_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Worldbane" },
  { id: 'silvershowerHeartstrings', enkaItemId: 15513, name: "Silvershower Heartstrings", tier: 'five_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Arcdange" },
  { id: 'skywardHarp', enkaItemId: 15501, name: "Skyward Harp", tier: 'five_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Dvalin" },
  { id: 'theDaybreakChronicles', enkaItemId: 15515, name: "The Daybreak Chronicles", tier: 'five_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Arianna" },
  { id: 'theFirstGreatMagic', enkaItemId: 15512, name: "The First Great Magic", tier: 'five_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Pledge" },
  { id: 'thunderingPulse', enkaItemId: 15509, name: "Thundering Pulse", tier: 'five_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Narukami" },
  { id: 'alleyHunter', enkaItemId: 15410, name: "Alley Hunter", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Outlaw" },
  { id: 'blackcliffWarbow', enkaItemId: 15408, name: "Blackcliff Warbow", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Blackrock" },
  { id: 'chainBreaker', enkaItemId: 15431, name: "Chain Breaker", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Isikhulu" },
  { id: 'cloudforged', enkaItemId: 15426, name: "Cloudforged", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Ultimatum" },
  { id: 'compoundBow', enkaItemId: 15407, name: "Compound Bow", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Exotic" },
  { id: 'endOfTheLine', enkaItemId: 15418, name: "End of the Line", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Fin" },
  { id: 'fadingTwilight', enkaItemId: 15411, name: "Fading Twilight", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Fallensun" },
  { id: 'favoniusWarbow', enkaItemId: 15401, name: "Favonius Warbow", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Zephyrus" },
  { id: 'flowerWreathedFeathers', enkaItemId: 15430, name: "Flower-Wreathed Feathers", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Umpakati" },
  { id: 'hamayumi', enkaItemId: 15414, name: "Hamayumi", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Bakufu" },
  { id: 'ibisPiercer', enkaItemId: 15419, name: "Ibis Piercer", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Ibis" },
  { id: 'kingSSquire', enkaItemId: 15417, name: "King\u0027s Squire", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Arakalari" },
  { id: 'mitternachtsWaltz', enkaItemId: 15412, name: "Mitternachts Waltz", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Nachtblind" },
  { id: 'mouunSMoon', enkaItemId: 15416, name: "Mouun\u0027s Moon", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Maria" },
  { id: 'predator', enkaItemId: 15415, name: "Predator", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Predator" },
  { id: 'prototypeCrescent', enkaItemId: 15406, name: "Prototype Crescent", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Proto" },
  { id: 'rainbowSerpentSRainBow', enkaItemId: 15434, name: "Rainbow Serpent\u0027s Rain Bow", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_ElegguaBow" },
  { id: 'rangeGauge', enkaItemId: 15427, name: "Range Gauge", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Mechanic" },
  { id: 'royalBow', enkaItemId: 15404, name: "Royal Bow", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Theocrat" },
  { id: 'rust', enkaItemId: 15405, name: "Rust", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Recluse" },
  { id: 'sacrificialBow', enkaItemId: 15403, name: "Sacrificial Bow", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Fossil" },
  { id: 'scionOfTheBlazingSun', enkaItemId: 15424, name: "Scion of the Blazing Sun", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Gurabad" },
  { id: 'sequenceOfSolitude', enkaItemId: 15432, name: "Sequence of Solitude", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Stinger" },
  { id: 'snareHook', enkaItemId: 15433, name: "Snare Hook", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Ilmarinen" },
  { id: 'songOfStillness', enkaItemId: 15425, name: "Song of Stillness", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Vorpal" },
  { id: 'stringless', enkaItemId: 15402, name: "The Stringless", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Troupe" },
  { id: 'theViridescentHunt', enkaItemId: 15409, name: "The Viridescent Hunt", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Viridescent" },
  { id: 'windblumeOde', enkaItemId: 15413, name: "Windblume Ode", tier: 'four_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Fleurfair" },
  { id: 'messenger', enkaItemId: 15305, name: "Messenger", tier: 'three_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Msg" },
  { id: 'ravenBow', enkaItemId: 15301, name: "Raven Bow", tier: 'three_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Crowfeather" },
  { id: 'recurveBow', enkaItemId: 15303, name: "Recurve Bow", tier: 'three_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Curve" },
  { id: 'sharpshooterSOath', enkaItemId: 15302, name: "Sharpshooter\u0027s Oath", tier: 'three_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Arjuna" },
  { id: 'slingshot', enkaItemId: 15304, name: "Slingshot", tier: 'three_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Sling" },
  { id: 'seasonedHunterSBow', enkaItemId: 15201, name: "Seasoned Hunter\u0027s Bow", tier: 'two_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Old" },
  { id: 'hunterSBow', enkaItemId: 15101, name: "Hunter\u0027s Bow", tier: 'one_star', weaponClass: 'bow', iconAssetName: "UI_EquipIcon_Bow_Hunters" },
  { id: 'aThousandFloatingDreams', enkaItemId: 14511, name: "A Thousand Floating Dreams", tier: 'five_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Ayus" },
  { id: 'cashflowSupervision', enkaItemId: 14513, name: "Cashflow Supervision", tier: 'five_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Wheatley" },
  { id: 'craneSEchoingCall', enkaItemId: 14515, name: "Crane\u0027s Echoing Call", tier: 'five_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_MountainGale" },
  { id: 'everlastingMoonglow', enkaItemId: 14506, name: "Everlasting Moonglow", tier: 'five_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Kaleido" },
  { id: 'jadefallSSplendor', enkaItemId: 14505, name: "Jadefall\u0027s Splendor", tier: 'five_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Morax" },
  { id: 'kaguraSVerity', enkaItemId: 14509, name: "Kagura\u0027s Verity", tier: 'five_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Narukami" },
  { id: 'lostPrayer', enkaItemId: 14502, name: "Lost Prayer to the Sacred Winds", tier: 'five_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Fourwinds" },
  { id: 'memoryOfDust', enkaItemId: 14504, name: "Memory of Dust", tier: 'five_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Kunwu" },
  { id: 'nightweaverSLookingGlass', enkaItemId: 14520, name: "Nightweaver\u0027s Looking Glass", tier: 'five_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_MenulisRing" },
  { id: 'nocturneSCurtainCall', enkaItemId: 14522, name: "Nocturne\u0027s Curtain Call", tier: 'five_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Brisingamen" },
  { id: 'reliquaryOfTruth', enkaItemId: 14521, name: "Reliquary of Truth", tier: 'five_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Sistrum" },
  { id: 'skywardAtlas', enkaItemId: 14501, name: "Skyward Atlas", tier: 'five_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Dvalin" },
  { id: 'starcallerSWatch', enkaItemId: 14517, name: "Starcaller\u0027s Watch", tier: 'five_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Figurines" },
  { id: 'sunnyMorningSleepIn', enkaItemId: 14518, name: "Sunny Morning Sleep-In", tier: 'five_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_SakuraFan" },
  { id: 'surfSUp', enkaItemId: 14516, name: "Surf\u0027s Up", tier: 'five_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_MechaPufferfish" },
  { id: 'tomeOfTheEternalFlow', enkaItemId: 14514, name: "Tome of the Eternal Flow", tier: 'five_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Iudex" },
  { id: 'tulaytullahSRemembrance', enkaItemId: 14512, name: "Tulaytullah\u0027s Remembrance", tier: 'five_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Alaya" },
  { id: 'vividNotions', enkaItemId: 14519, name: "Vivid Notions", tier: 'five_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_VaresaTransformer" },
  { id: 'ashGravenDrinkingHorn', enkaItemId: 14427, name: "Ash-Graven Drinking Horn", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_ConchSprayer" },
  { id: 'balladOfTheBoundlessBlue', enkaItemId: 14426, name: "Ballad of the Boundless Blue", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_DandelionPoem" },
  { id: 'blackcliffAgate', enkaItemId: 14408, name: "Blackcliff Agate", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Blackrock" },
  { id: 'blackmarrowLantern', enkaItemId: 14433, name: "Blackmarrow Lantern", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Ilmarinen" },
  { id: 'dawningFrost', enkaItemId: 14434, name: "Dawning Frost", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Ziedas" },
  { id: 'dodocoTales', enkaItemId: 14413, name: "Dodoco Tales", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Ludiharpastum" },
  { id: 'etherlightSpindlelute', enkaItemId: 14432, name: "Etherlight Spindlelute", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_SeeliesLute" },
  { id: 'eyeOfPerception', enkaItemId: 14409, name: "Eye of Perception", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Truelens" },
  { id: 'favoniusCodex', enkaItemId: 14401, name: "Favonius Codex", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Zephyrus" },
  { id: 'flowingPurity', enkaItemId: 14425, name: "Flowing Purity", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Vorpal" },
  { id: 'frostbearer', enkaItemId: 14412, name: "Frostbearer", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Everfrost" },
  { id: 'fruitOfFulfillment', enkaItemId: 14417, name: "Fruit of Fulfillment", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Arakalari" },
  { id: 'hakushinRing', enkaItemId: 14414, name: "Hakushin Ring", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Bakufu" },
  { id: 'mappaMare', enkaItemId: 14407, name: "Mappa Mare", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Exotic" },
  { id: 'oathswornEye', enkaItemId: 14415, name: "Oathsworn Eye", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Jyanome" },
  { id: 'prototypeAmber', enkaItemId: 14406, name: "Prototype Amber", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Proto" },
  { id: 'ringOfYaxche', enkaItemId: 14431, name: "Ring of Yaxche", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Isikhulu" },
  { id: 'royalGrimoire', enkaItemId: 14404, name: "Royal Grimoire", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Theocrat" },
  { id: 'sacrificialFragments', enkaItemId: 14403, name: "Sacrificial Fragments", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Fossil" },
  { id: 'sacrificialJade', enkaItemId: 14424, name: "Sacrificial Jade", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Yue" },
  { id: 'solarPearl', enkaItemId: 14405, name: "Solar Pearl", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Resurrection" },
  { id: 'theWidsith', enkaItemId: 14402, name: "The Widsith", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Troupe" },
  { id: 'wanderingEvenstar', enkaItemId: 14416, name: "Wandering Evenstar", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Pleroma" },
  { id: 'waveridingWhirl', enkaItemId: 14430, name: "Waveriding Whirl", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Umpakati" },
  { id: 'wineAndSong', enkaItemId: 14410, name: "Wine and Song", tier: 'four_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Outlaw" },
  { id: 'emeraldOrb', enkaItemId: 14304, name: "Emerald Orb", tier: 'three_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Jade" },
  { id: 'magicGuide', enkaItemId: 14301, name: "Magic Guide", tier: 'three_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Intro" },
  { id: 'otherworldlyStory', enkaItemId: 14303, name: "Otherworldly Story", tier: 'three_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Lightnov" },
  { id: 'thrillingTalesOfDragonSlayers', enkaItemId: 14302, name: "Thrilling Tales of Dragon Slayers", tier: 'three_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Pulpfic" },
  { id: 'twinNephrite', enkaItemId: 14305, name: "Twin Nephrite", tier: 'three_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Phoney" },
  { id: 'pocketGrimoire', enkaItemId: 14201, name: "Pocket Grimoire", tier: 'two_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Pocket" },
  { id: 'apprenticeSNotes', enkaItemId: 14101, name: "Apprentice\u0027s Notes", tier: 'one_star', weaponClass: 'catalyst', iconAssetName: "UI_EquipIcon_Catalyst_Apprentice" },
] as const satisfies readonly WeaponCatalogEntry[];

export const WEAPON_ID_BY_ENKA_ITEM_ID = Object.fromEntries(
  WEAPON_CATALOG.map((weapon) => [weapon.enkaItemId, weapon.id]),
) as Record<number, string>;

